-- ====================================================================
-- ESQUEMA COMPLETO DE BASE DE DATOS SUPABASE - LOPEZ ARQ
-- ====================================================================

-- 1. Tabla de Usuarios
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'PROYECTISTA', -- 'ADMIN' o 'PROYECTISTA'
  rate_per_hour NUMERIC(12, 2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.users TO anon, authenticated, service_role;

-- 2. Tabla de Obras / Proyectos
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) UNIQUE NOT NULL,
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- 'ACTIVE' o 'COMPLETED'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);
ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.projects TO anon, authenticated, service_role;

-- 3. Tabla de Cargas de Horas (Timesheets)
CREATE TABLE IF NOT EXISTS public.timesheets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  work_date DATE NOT NULL DEFAULT CURRENT_DATE,
  start_time VARCHAR(10) DEFAULT '08:00',
  end_time VARCHAR(10) DEFAULT '12:00',
  hours NUMERIC(6, 2) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);
ALTER TABLE public.timesheets DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.timesheets TO anon, authenticated, service_role;

-- 4. Tabla de Gastos y Reembolsos (Oficina u Obras)
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES projects(id) ON DELETE SET NULL,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  category VARCHAR(50) NOT NULL DEFAULT 'OFFICE', -- 'OFFICE' o 'PROJECT'
  description TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- 'PENDING' o 'REIMBURSED'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);
ALTER TABLE public.expenses DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.expenses TO anon, authenticated, service_role;
